CREATE DATABASE assignment_db;

CREATE TABLE IF NOT EXISTS Employees (
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(150) UNIQUE NOT NULL,
salary INTEGER NOT NULL,
department VARCHAR(50) NOT NULL
);